### ISSUE TITLE
NPM Update

### ISSUE THREAD

**Issue by browniefed** [metatribal/xmlToJSON#13]
Hey, could you do an npm publish with the latest version, it would be much appreciated.

**Comment by metatribal** [comment]
I'm sorry.  This library is not intended for use in Node as it requires a compatible W3C DOM API - some people have reported success using xmldom.

**Comment by browniefed** [comment]
@metatribal I understand, however npm is used more for than just Node, it's used for front end packages as well. It's essentially a JavaScript package manager.

**Comment by metatribal** [comment]
Gotcha.  I have an updated package.json file from another contributor.  I
will review it and try to get it pushed to npm tomorrow morning.

**Comment by metatribal** [comment]
The project now has a project file and can be loaded via npm.  Thanks for the suggestion.  Closing.

**Comment by metatribal** [comment]
Typo - package file ; and can be loaded as a git repo via npm
