### ISSUE TITLE
Please publish new version, for JSPM compatibility

### ISSUE THREAD

**Issue by kylecordes** [metatribal/xmlToJSON#15]
It appears that the very most recent commit of this project is compatible with JSPM, but all previous versions are not. Therefore, the following fails:

```
jspm install github:metatribal/xmlToJSON
```

(Or rather, the command works, but the module cannot be loaded)

But this succeeds:

```
jspm install github:metatribal/xmlToJSON@master
```

Therefore, please "version" the project again so that this latest commit is published as a version. That will make it "just work" without having to know anything about the above.

(On a broader note, it's a new world out there! Until the last few years, nearly everyone was just bringing libraries in with a script tag. Now there is a rapidly increasing expectation that module loaders will work, whether it is browserify with require, JSPM, etc. It is a bunch of stuff to get used to, but the development experience is vastly improved for large complex applications.)

**Comment by metatribal** [comment]
Thanks for catch.  It should be fixed now - let me know if it still does not work for you.

**Comment by kylecordes** [comment]
Yes, it works well now, thank you.
