### ISSUE TITLE
Update module on npm

### ISSUE THREAD

**Issue by MDSLKTR** [metatribal/xmlToJSON#20]
Hello,

is it possible to make this available on npm again with the newest version? Newest npm version currently is 1.1.0, which is kind of outdated.

Thanks in Advance,
Simon

**Comment by metatribal** [comment]
Currently packing up my house :). I will try to update it this weekend.

**Comment by MDSLKTR** [comment]
No worries mate :), thank you for the heads up :+1:

**Comment by derhuerst** [comment]
ping

**Comment by brandonshults** [comment]
Hello, thank you for your work on xmlToJSON.  I too would like to request an update for the npm module.

Thanks!

**Comment by Grisu118** [comment]
Push

**Comment by tavurth** [comment]
Ping, I actually went into the source code to fix this.
Cloned the repository to push changes, and found the changes already present.

Can we fix this please?

**Comment by metatribal** [comment]
Sorry everyone!  I've been traveling for the past year or so.
The latest version has been pushed and I am working on a 2.0 release (next month)
