### ISSUE TITLE
Cannot get it working with latest angular-cli with webpack

### ISSUE THREAD

**Issue by simmode** [metatribal/xmlToJSON#26]
following directions given here: [http://www.typescriptlang.org/docs/handbook/declaration-files/consumption.html].
I did the following:
`npm install xmltojson --save`
`npm install @types/xmltojson --save-dev`

Then in app.component.ts add this line:
`import * as xmltojson from 'xmltojson'`

Yet xmltojson is not initialized correctly.
Comes back as empty javascript object

**Comment by metatribal** [comment]
Are you using this in node?  xmlToJSON does not work in nodejs since node does not provide a compliant DOM API.

**Comment by simmode** [comment]
not sure if that's it, i'm serving from angular-cli using:
`ng serve`

My import call is in the app component typescript file.
At compile time it's able to find the defined object and types, but when I run it and debug code in chrome  it's just an empty javascript object.

**Comment by joejordanbrown** [comment]
@simmode 

Have you created the TypeScript  type definitions?

I use it by including it in `angular-cli.json `

`"scripts": ["assets/js/xmlToJSON.js"],`

And instead of import use
 `declare var xmlToJSON: any;`

Works perfectly that way until a .d.ts is created for xmlToJSON.

**Comment by metatribal** [comment]
@simmode Thanks for the answer.  If you have a definition file for TypeScript, I'd be happy to incorporate it.
