### ISSUE TITLE
Doesn't work in NodeJS

### ISSUE THREAD

**Issue by anotherpit** [metatribal/xmlToJSON#27]
While README says the library has _no external dependencies_, it actually depends on global `window` object and `DOMParser` or `ActiveXObject` classes. Thus, the library cannot be used in NodeJS. @metatribal, please, mention this in README.

**Comment by metatribal** [comment]
The readme does mention that it is for use within a browser, but I will
consider being more explicit as I get several questions about using this
library in node.

Thanks.

**Comment by Nokel81** [comment]
Is it possible to have it work within NodeJS?

**Comment by sethb0** [comment]
Possible to make it work in node with an additional dependency (`xmldom`) and a monkeypatch:
```js
const { DOMParser } = require('xmldom');
const xmlToJSON = require('xmlToJSON');
xmlToJSON.stringToXML = (string) => new DOMParser().parseFromString(string, 'text/xml');
```

**Comment by metatribal** [comment]
Nice.  I will give this a test when I'm back in the lab and add it to the
documentation.

Thanks.

**Comment by metatribal** [comment]
Added @sethb0's workaround to the readme.
