### ISSUE TITLE
syntax error display on console when call  xml_str2json() on firefox

### ISSUE THREAD

**Issue by Vincentyuan** [metatribal/xmlToJSON#28]
when i call the method xml_str2json() to convert xml to json object, i always get the error "syntax error".

But the website can continue work well. 

And I use firefox 52.

**Comment by julmot** [comment]
Where did you take the method `xml_str2json()` from? As far as I know there's only the `parseString` method!

**Comment by Vincentyuan** [comment]
aha, yes , you are right , your script is right and i am very sorry , i use another lib for this and they have that issue which contains this issue.
