### ISSUE TITLE
How to force to dispaly 0 after decimal?

### ISSUE THREAD

**Issue by adishri22** [metatribal/xmlToJSON#30]
I have response which is in an xml file. When I am using this parser and converting json for some attributes which has value like '2.0' or '5.0' it is giving me simply '2' and '5'. How I can force it to give me '2.0' and '5.0'.

**Comment by metatribal** [comment]
This is a side effect of the `grokAttr` and `grokText` attributes being set to true.  The type checking code in this library uses the javascript `parseFloat()` method which truncates trailing zeros.  For your specific use case, try setting the `grokAttr` and/or `grokText` attributes to false.  This will leave the values untouched as well as disable smart truthyness.

If this doesn't work for you, let me know and I will see what I can do.
