### ISSUE TITLE
Question: Difference between textKey and valueKey?

### ISSUE THREAD

**Issue by julmot** [metatribal/xmlToJSON#7]
While working with the plugin two questions came up which aren't answered in the documentation:
* Why there are two different key names for text and value?
* When the plugin will use textKey and when valueKey?

**Comment by metatribal** [comment]
textKey is the JSON key for the XML text node's value.
valueKey is the JSON key used for an XML attribute's value.

Regarding DOM Node types: https://developer.mozilla.org/en-US/docs/Web/API/Node
Attributes are properties of the Element type: https://developer.mozilla.org/en-US/docs/Web/API/Element
